jobs:
- deployment: databaseDeployment
  displayName: 'Deploy Database'
  environment: prod
  variables:
  - group: env_globals
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../steps/download-artifact.yaml
          parameters:
            artifact: 'database'
            path: '$(Pipeline.Workspace)/database'
            patterns: '*.sql'