jobs:
- deployment: databaseDeployment
  displayName: 'Deploy Database'
  environment: prod
  variables:
  - group: env_globals
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:        
          - download: none
          - task: DownloadPipelineArtifact@2
            displayName: Download Artifact
            inputs:
              source: 'current'
              artifact: 'database'
              path: '$(Pipeline.Workspace)/database'
              patterns: '*.sql'