jobs:
- deployment: webAppDeployment
  displayName: 'Deploy Web App'
  environment: prod
  variables:
  - group: env_globals
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
          - download: none              
          - task: DownloadPipelineArtifact@2
            displayName: Download Artifact
            inputs:
              source: 'current'
              artifact: 'web-app'
              path: '$(Pipeline.Workspace)/web-app'          
          
          - task: replacetokens@3
            displayName: 'Replace tokens in .js files'
            inputs:
              rootDirectory: $(Pipeline.Workspace)/web-app/Obj-Twins-Games-Stats-App
              targetFiles: |
                **/main-es2015.*.js
                **/main-es5.*.js
              encoding: 'utf-8'
              escapeType: none
              actionOnMissing: 'fail'
