jobs:
- deployment: webApiDeployment
  displayName: Deploy Web Api
  environment: prod
  variables:
    - group: env_globals  
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../steps/download-artifact.yaml
          parameters:
            artifact: 'web-api'
            path: '$(Pipeline.Workspace)/web-api'        
          
        - task: replacetokens@3
          displayName: 'Replace tokens in .json files'
          inputs:
            rootDirectory: $(Pipeline.Workspace)/web-api/Obj.Twins.Games.Api
            targetFiles: '**/*.json'
            encoding: 'utf-8'
            escapeType: none
            actionOnMissing: 'fail'