jobs:
- deployment: webAppDeployment
  displayName: 'Deploy Web App'
  environment: prod
  variables:
  - group: env_globals
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
          - download: none
          
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '1b545c79-3af9-4a0d-9abf-bdc31562c282'
              definition: '14'
              buildVersionToDownload: 'latest'
              artifactName: 'web-app'
              targetPath: '$(Pipeline.Workspace)/web-app'          
          
          - task: replacetokens@3
            displayName: 'Replace tokens in .js files'
            inputs:
              rootDirectory: $(Pipeline.Workspace)/web-app/Obj-Twins-Games-Stats-App
              targetFiles: |
                **/main-es2015.*.js
                **/main-es5.*.js
              encoding: 'utf-8'
              escapeType: none
              actionOnMissing: 'fail'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: 'OBJ-Twins'
              WebAppName: 'obj-twins-games-app'
              packageForLinux: '$(Pipeline.Workspace)/web-app/Obj-Twins-Games-Stats-App'
            continueOnError: true
            enabled: false

          - task: FtpUpload@2
            displayName: 'Upload Web App'
            inputs:
              credentialsOption: 'inputs'
              serverUrl: 'ftps://waws-prod-am2-163.ftp.azurewebsites.windows.net'
              username: 'obj-twins-games-web\$obj-twins-games-web'
              password: '$(App.Ftp.Password)'
              rootDirectory: '$(Pipeline.Workspace)/web-app/Obj-Twins-Games-Stats-App'
              filePatterns: '**'
              remoteDirectory: '/site/wwwroot'
              clean: false
              cleanContents: true
              preservePaths: true
              trustSSL: true