trigger: none
pr: none
resources:
  pipelines:
    - pipeline: build-pipeline
      source: ci-build


name: "$(Date:yyy).$(Date:MM).$(Date:dd)r$(Rev:rr)_$(SourceBranchName)"

jobs:
  - template: templates/deploy/jobs/deploy-web-api.yaml
  - template: templates/deploy/jobs/deploy-database.yaml
  - template: templates/deploy/jobs/deploy-web-app.yaml