trigger:
  - develop
  - master

pr:
  branches:
    include: [develop, master, releases/*]
  autoCancel: true
  
name: "$(Date:yyy).$(Date:MM).$(Date:dd)r$(Rev:rr)_$(SourceBranchName)"
jobs:
  - template: templates/build/jobs/build-web-api.yaml
  - template: templates/build/jobs/build-web-app.yaml