trigger:
  - develop
  - master
  
name: "$(Date:yyy).$(Date:MM).$(Date:dd)r$(Rev:rr)_$(SourceBranchName)"
stages:
  - stage: Build
    pool:
      vmImage: 'windows-latest'
    jobs:
      - template: templates/build/jobs/build-web-api.yaml
      - template: templates/build/jobs/build-web-app.yaml
      
  - stage: Deploy
    dependsOn: Build
    pool:
      vmImage: 'windows-latest'
    jobs:
      - template: templates/deploy/jobs/deploy-web-api.yaml
      - template: templates/deploy/jobs/deploy-database.yaml
      - template: templates/deploy/jobs/deploy-web-app.yaml